### ISSUE TITLE
Android app for breast cancer detection using Deep learning.

### ISSUE THREAD

**Issue by rajat1994** [mari-linhares/mnist-android-tensorflow#2]
Hey ! @mari-linhares ... i saw your mnist android app ...nice work:)  What about an android app for breast cancer detection using deep learning? I  made an web app for it : https://warm-falls-58774.herokuapp.com/
Github link : https://github.com/rajat1994/WebApp-for-breast-cancer-detection. Android app for this will be a great project.
Thanks :)

**Comment by hereismari** [comment]
Hi @rajat1994, it does sound awesome! Follow the instructions in the README file to be sure that the app can use TensorFlow code and is good to go! Actually is simpler to do than it may sound!

Feel free to follow the instructions and do your own android app, if you want some help feel free to contact me (email is the best way).

Cheers, and have a nice day!
